Fix error messages
Vladacdc/TransIT.Client pull request #16
Opened 2019-08-04 16:04 UTC by BohdanBuhrii

2019-08-04 18:07 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-05 08:41 UTC, Vladacdc requested changes
Add to .gitignore .vscode

2019-08-05 08:42 UTC, Vladacdc commented
Better even update .gitingnore via [https://www.gitignore.io/](url)

2019-08-06 09:30 UTC, Vladacdc approved these changes

2019-08-06 09:33 UTC, VitalikRibiy approved these changes

2019-08-06 10:33 UTC, VitaliiMaksymiv approved these changes

2019-08-06 10:34 UTC, merged