PDF preview and paginating fix
Vladacdc/TransIT.Client pull request #20
Opened 2019-08-06 12:09 UTC by VitaliiMaksymiv

To make "PDF-preview" work, disable AdBlock

2019-08-06 12:25 UTC, Vladacdc submitted a review, later dismissed

2019-08-06 12:45 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-06 12:48 UTC, BohdanBuhrii requested changes
A lot of copy-paste. Please replace with some function like drowDocument()

2019-08-06 17:53 UTC, andriyshevchenko approved these changes

2019-08-07 11:09 UTC, BohdanBuhrii approved these changes

2019-08-07 11:57 UTC, closed without merging