Add parts to admin
Vladacdc/TransIT.Client pull request #39
Opened 2019-08-25 15:27 UTC by VitaliiMaksymiv

2019-08-25 18:19 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-27 04:26 UTC, igolovchuk commented on src/app/modules/admin/component/parts/create-part/create-part.component.ts
> +    const modalWindow: any = $('#createPart');
do not use jquery inside angular, we want to remove such dependencies, not add, use document.getElementById('elemid') or  @ViewChild('elemid')

2019-08-27 04:29 UTC, igolovchuk requested changes
see comment in file

2019-08-31 22:48 UTC, Vladacdc requested changes
PULL FROM DEV BEFORE MERGING

2019-08-31 22:48 UTC, Vladacdc commented on src/app/modules/admin/component/employees/employees.component.html
> +<div class="table-background border mt-3">
You do not need to add that, especially in top element of component, 'cuz everywhere is same margin.

2019-08-31 22:48 UTC, Vladacdc commented on src/app/modules/admin/component/parts/create-part/create-part.component.ts
> +    $('#createPart').on('hidden.bs.modal', function() {
if you are using angular forms, please use their reset

2019-08-31 22:48 UTC, Vladacdc commented on src/app/modules/admin/component/parts/create-part/create-part.component.ts
> +    $('#createPart').on('hidden.bs.modal', function() {
and better to do it on modal close click

2019-08-31 22:48 UTC, Vladacdc commented on src/app/modules/admin/component/parts/parts.component.spec.ts
> +  beforeEach(async(() => {
Are you sure tests work fine or you just adding them because you can?

2019-08-31 22:48 UTC, Vladacdc commented on src/app/modules/admin/component/parts/parts.component.ts
> +  @ViewChild("table") table: MatFspTableComponent;
Please install TSLint

2019-08-31 22:49 UTC, Vladacdc commented
btw you can leave admin navbar, 'cuz i misdeleted it.

2019-08-31 22:57 UTC, Vladacdc commented on src/app/modules/admin/component/parts/create-part/create-part.component.ts
> +    $('#createPart').on('hidden.bs.modal', function() {
Are you even reading what @igolovchuk writing you about jquery inside angular?

2019-08-31 23:25 UTC, closed without merging