Change the design and some logic of the filter panel for issues
Vladacdc/TransIT.Client pull request #40
Opened 2019-08-26 21:18 UTC by VitaliiMaksymiv

### Before:
![image](https://user-images.githubusercontent.com/34031693/63717107-28dcab00-c850-11e9-8677-176a59d7db8e.png)

### After:
![image](https://user-images.githubusercontent.com/34031693/63724218-ec18b000-c85f-11e9-9b45-246a998a6889.png)

2019-08-26 21:32 UTC, andriyshevchenko reviewed
Please make typesript code appear each statement on new line in the HTML
![зображення](https://user-images.githubusercontent.com/26359203/63725364-cfca4280-c862-11e9-95a1-6761a666d6bc.png)

2019-08-27 04:32 UTC, igolovchuk commented on src/app/modules/shared/shared.module.ts
> +    {provide: MAT_DATE_LOCALE, useValue: 'en-GB'}
why en-GB not uk or uk-UA?

2019-08-27 08:53 UTC, BohdanBuhrii requested changes
These changes make the element less functional, which is why it does not meet the requirements. Also the quality of the code and its comprehensibility is much worse than before.

2019-08-27 11:19 UTC, BohdanBuhrii commented on src/app/modules/shared/components/filters-tabs/filters-tabs.component.html
> +          (click)="selectedGroup=undefined;
move logic to function

2019-08-27 11:19 UTC, BohdanBuhrii reviewed
see comments

2019-08-27 11:20 UTC, BohdanBuhrii approved these changes

2019-08-27 13:05 UTC, igolovchuk approved these changes

2019-08-27 13:27 UTC, andriyshevchenko approved these changes

2019-08-27 14:26 UTC, merged