Translate FilterTab and Calendar and date-format
Vladacdc/TransIT.Client pull request #43
Opened 2019-08-28 14:43 UTC by VitaliiMaksymiv

2019-08-28 15:00 UTC, BohdanBuhrii commented on src/app/app.module.ts
> +<<<<<<< HEAD
It looks like you forgot something)

2019-08-28 15:01 UTC, BohdanBuhrii requested changes
see comment in file

2019-08-28 16:00 UTC, BohdanBuhrii submitted a review, later dismissed

2019-08-28 21:29 UTC, andriyshevchenko submitted a review, later dismissed
^-^

2019-08-28 22:55 UTC, andriyshevchenko approved these changes

2019-08-29 11:08 UTC, SviatoslavBachynskyi approved these changes

2019-08-29 11:09 UTC, BohdanBuhrii approved these changes

2019-08-29 11:09 UTC, merged