Improve ux with documents
Vladacdc/TransIT.Client pull request #45
Opened 2019-08-31 10:16 UTC by SviatoslavBachynskyi

2019-08-31 10:26 UTC, Vladacdc requested changes

2019-08-31 10:26 UTC, Vladacdc commented on src/app/custom-errors.ts
> +  ...CUSTOM_ERRORS,
Now we are not using this code. It is deprecated. Look how it's done in core/validator or login form.

2019-08-31 10:26 UTC, Vladacdc commented on src/app/modules/shared/components/global-document/document/create-document/create-document.component.html
> +                    <div class="form-group" [customErrorMessages]="CustomPDFErrorMessages">
Use here my validator, just add specific error to validatorComponent.

2019-08-31 10:30 UTC, Vladacdc commented
Also it would be nice to add translation to documents.

2019-08-31 10:42 UTC, igolovchuk approved these changes

2019-08-31 12:38 UTC, BohdanBuhrii approved these changes

2019-09-01 15:58 UTC, VitaliiMaksymiv approved these changes

2019-09-01 18:32 UTC, Vladacdc approved these changes

2019-09-01 18:32 UTC, merged