Rework tables 17.09.2019 ribii
Vladacdc/TransIT.Client pull request #66
Opened 2019-09-19 20:31 UTC by VitalikRibiy

2019-09-19 20:36 UTC, VitalikRibiy commented
Do not delete branch !

2019-09-19 20:37 UTC, Vladacdc submitted a review, later dismissed

2019-09-19 22:30 UTC, VitaliiMaksymiv submitted a review, later dismissed

2019-09-20 03:59 UTC, BohdanBuhrii requested changes
Fix bug with modal forms

2019-09-20 09:51 UTC, BohdanBuhrii approved these changes

2019-09-20 09:54 UTC, VasilDun approved these changes

2019-09-20 09:55 UTC, konerokua approved these changes

2019-09-20 09:57 UTC, merged